#!/bin/bash
# ============================================
# Firebase Deployment Check Script
# Script untuk verifikasi konfigurasi Firebase
# ============================================

set -e  # Exit on error

echo "🔍 ============================================"
echo "🔍 FIREBASE DEPLOYMENT CONFIGURATION CHECK"
echo "🔍 ============================================"
echo ""

# 1. Check Firebase JSON file
echo "📄 1. Checking firebase.json..."
if [ ! -f "firebase.json" ]; then
    echo "❌ ERROR: firebase.json not found!"
    echo "💡 Solution: Run 'firebase init' or create firebase.json manually"
    exit 1
else
    echo "✅ firebase.json found"
    
    # Validate JSON syntax
    if command -v jq &> /dev/null; then
        if jq empty firebase.json 2>/dev/null; then
            echo "✅ Valid JSON syntax"
        else
            echo "⚠️ Warning: JSON syntax may have issues"
        fi
    fi
fi

echo ""

# 2. Check Firebase config file
echo "⚙️  2. Checking Firebase configuration..."
if [ -f ".firebaserc" ]; then
    echo "✅ .firebaserc found"
    
    # Extract project ID
    if command -v jq &> /dev/null; then
        PROJECTS=$(jq '.projects' .firebaserc 2>/dev/null || echo "")
        DEFAULT_PROJECT=$(jq -r '.default' .firebaserc 2>/dev/null || echo "")
        
        if [ -n "$PROJECTS" ] && [ "$PROJECTS" != "null" ]; then
            echo "📁 Projects configuration:"
            echo "$PROJECTS" | jq '.'
        fi
        
        if [ -n "$DEFAULT_PROJECT" ] && [ "$DEFAULT_PROJECT" != "null" ]; then
            echo "🎯 Default project: $DEFAULT_PROJECT"
        fi
    else
        # Fallback without jq
        echo "📋 .firebaserc content:"
        cat .firebaserc
    fi
else
    echo "⚠️ Warning: .firebaserc not found"
    echo "💡 Info: This file is auto-generated by 'firebase init'"
fi

echo ""

# 3. Check Hosting configuration
echo "🌐 3. Checking Hosting configuration..."
HOSTING_CONFIG=$(grep -A 10 '"hosting"' firebase.json)

if [ -n "$HOSTING_CONFIG" ]; then
    echo "✅ Hosting configuration found"
    
    # Extract public directory
    PUBLIC_DIR=$(grep -o '"public":[[:space:]]*"[^"]*"' firebase.json | head -1 | cut -d'"' -f4)
    if [ -n "$PUBLIC_DIR" ]; then
        echo "📂 Public directory: $PUBLIC_DIR"
        
        # Check if directory exists
        if [ -d "$PUBLIC_DIR" ]; then
            echo "✅ Public directory exists"
            
            # Count files
            FILE_COUNT=$(find "$PUBLIC_DIR" -type f | wc -l)
            echo "📊 Files count: $FILE_COUNT"
            
            # List important files
            echo "📋 Important files:"
            find "$PUBLIC_DIR" -maxdepth 2 -name "*.html" -o -name "*.js" -o -name "*.css" | head -5
        else
            echo "⚠️ Warning: Public directory '$PUBLIC_DIR' not found!"
            echo "💡 Info: This directory should contain your built files"
        fi
    else
        echo "⚠️ Warning: 'public' directory not specified in firebase.json"
    fi
    
    # Check for rewrites/redirects
    if grep -q '"rewrites"' firebase.json; then
        echo "🔄 Rewrites configuration: Yes"
    fi
    
    if grep -q '"redirects"' firebase.json; then
        echo "↪️  Redirects configuration: Yes"
    fi
else
    echo "❌ ERROR: Hosting not configured in firebase.json"
    echo "💡 Solution: Make sure 'hosting' section exists in firebase.json"
    exit 1
fi

echo ""

# 4. Check build output (if Angular/React/Vue)
echo "🏗️  4. Checking build configuration..."
if [ -f "angular.json" ]; then
    echo "⚡ Framework detected: Angular"
    
    # Get Angular output path
    ANGULAR_OUTPUT=$(grep -o '"outputPath":[[:space:]]*"[^"]*"' angular.json | head -1 | cut -d'"' -f4)
    if [ -n "$ANGULAR_OUTPUT" ]; then
        echo "📁 Angular output path: $ANGULAR_OUTPUT"
        
        # Check if matches Firebase public directory
        if [ -n "$PUBLIC_DIR" ] && [ "$ANGULAR_OUTPUT" != "$PUBLIC_DIR" ]; then
            echo "⚠️ Warning: Angular output path ($ANGULAR_OUTPUT) doesn't match Firebase public directory ($PUBLIC_DIR)"
            echo "💡 Tip: Update firebase.json or angular.json to match"
        fi
    fi
    
elif [ -f "package.json" ]; then
    echo "📦 Node.js project detected"
    
    # Check build script
    if grep -q '"build"' package.json; then
        echo "🔨 Build script: Available"
    else
        echo "⚠️ Warning: No build script in package.json"
    fi
    
    # Check if it's React/Vue
    if grep -q '"react"' package.json || grep -q '"react-scripts"' package.json; then
        echo "⚛️  Framework detected: React"
    elif grep -q '"vue"' package.json; then
        echo "🟢 Framework detected: Vue.js"
    fi
fi

echo ""

# 5. Check dependencies
echo "📦 5. Checking dependencies..."
if [ -f "package.json" ]; then
    echo "✅ package.json found"
    
    # Check Firebase tools in dependencies
    if grep -q '"firebase"' package.json || grep -q '"firebase-tools"' package.json; then
        echo "🔥 Firebase SDK/tools: Included"
    else
        echo "ℹ️  Firebase SDK not in package.json (not required for hosting)"
    fi
fi

echo ""

# 6. Final summary
echo "✅ ============================================"
echo "✅ CHECK COMPLETED SUCCESSFULLY!"
echo "✅ ============================================"
echo ""
echo "📋 NEXT STEPS:"
echo "1. Run build command: npm run build"
echo "2. Verify files in: ${PUBLIC_DIR:-'public directory'}"
echo "3. Test locally: firebase serve"
echo "4. Deploy: firebase deploy --only hosting"
echo ""
echo "🚀 Ready for deployment!"